export const AUTH_LOAD = 'AUTH_LOAD';
export const AUTH_LOGIN = 'AUTH_SUCCESS';
export const AUTH_AVAILABILITY_SUCCESS = 'AUTH_AVAILABILITY_SUCCESS';
export const AUTH_AVAILABILITY_FAILED = 'AUTH_AVAILABILITY_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
